In [2]:
import numpy as np
import cv2
import time

In [3]:
img = cv2.imread("lena.png",cv2.IMREAD_GRAYSCALE)
img=cv2.resize(img,(256,256))
cv2.imwrite("lenaa.jpg" , img )

True

In [13]:
print(img)

[[162 162 159 ... 168 170 141]
 [162 162 159 ... 168 170 141]
 [163 159 160 ... 157 150 115]
 ...
 [ 51  51  53 ...  81  92  91]
 [ 44  48  50 ...  92 101  98]
 [ 43  56  50 ... 101 102 106]]


In [44]:
def encryption_function(image):
    timg=image
    print(timg)
    r=3.62
    x=[0.7]
    row=image.shape[0]
    col=image.shape[1]
    s=row*col
    for i in range(s-1):
        x.append(r*x[-1]*(1-x[-1]))
    # print(len(x))
    # print(len(set(x)))
    indices={}
    for index,value in enumerate(x):
        indices[value]=index
    
    x.sort()
    _timg=[]
    for i in range(row):
        for j in range(col):
            _timg.append(timg[i][j])
    # print(_timg)
    for i in range(len(_timg)):
        _timg[i],_timg[indices[x[i]]]=_timg[indices[x[i]]],_timg[i]     #assuming all valules are different

    #confusion creation ends
    print("confusion")
    #print(_timg)
    #creating diffusion key
    p=3.628
    k=[0.632]
    import math
    for i in range(s-1):
        k.append(math.cos(p*math.acos(k[-1])))
    for i in range(len(k)):
        k[i]=abs(round(k[i]*255))
    ktemp=circshift(k)
    key=np.bitwise_xor(k,ktemp)

    #diffusion key creation ended
  #the final encryption begin
    _timg=np.array(_timg).astype('uint8')
    
    key=np.array(key).astype('uint8')
    _timg=np.bitwise_xor(key,_timg)
    print("enc")
    print(_timg)
    himg=_timg.reshape(256,256)
    cv2.imwrite('encrptedlena.png', himg)
    '''cv2.imshow('test_encrypted',himg)
    cv2.imshow('original',image)
    while True:
        if cv2.waitKey(30)==ord('a'):
            break
    return _timg'''
    #start decryption
    
    _timg=np.array(_timg).astype('uint8')
    key=np.array(key).astype('uint8')
    _timg=np.bitwise_xor(key,_timg)
    for i in range(len(_timg)-1,1,-1):
        _timg[i],_timg[indices[x[i]]]=_timg[indices[x[i]]],_timg[i]
        
    print("hello")
    print(_timg)
    #assuming all valules are different

    himg1=_timg.reshape(256,256)
    print(himg1)
    cv2.imwrite('decyptedlena.png', himg1)
    #return _timg 


    #end decryption

    #test the decryption  


In [23]:
def circshift(arr,shift=1):
    while shift:
        key=arr[-1]
        for i in range(len(arr)-1,0,-1):
            arr[i]=arr[i-1]
        arr[0]=key
        shift-=1

    return arr

In [45]:
encryption_function(img)

[[162 162 159 ... 168 170 141]
 [162 162 159 ... 168 170 141]
 [163 159 160 ... 157 150 115]
 ...
 [ 51  51  53 ...  81  92  91]
 [ 44  48  50 ...  92 101  98]
 [ 43  56  50 ... 101 102 106]]
confusion
enc
[131  97 140 ... 132 181 165]
hello
[155  92 159 ... 101 102 106]
[[155  92 159 ... 168 170 141]
 [162 162 159 ... 168 170 141]
 [163 159 160 ... 157 150 115]
 ...
 [ 51  51  53 ...  81  92  91]
 [ 44  48  50 ...  92 101  98]
 [ 43  56  50 ... 101 102 106]]
